# Generated by Django 3.1.5 on 2021-01-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('temperatura', models.IntegerField()),
                ('fecha_de_emicion', models.DateField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.persona')),
            ],
        ),
    ]
