# Generated by Django 3.1.5 on 2021-01-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperatura',
            name='persona',
        ),
    ]
