# Generated by Django 3.1.5 on 2021-01-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210114_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nombre',
            new_name='produccion',
        ),
    ]
